object_list:
  - name: sticky_notes
    group: green
  - name: book
    group: red
  - name: snacks
    group: green
  - name: biscuits
    group: red
  - name: eraser
    group: red
  - name: soap2
    group: green
  - name: soap
    group: green
  - name: glue
    group: red